// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaffleKing.Models;

#nullable disable

namespace RaffleKing.Migrations
{
    [DbContext(typeof(RaffleContext))]
    [Migration("20230311042914_asas")]
    partial class asas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("RaffleKing.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("U_Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_RoleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_UserNameShortCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("RaffleKing.Models.RaffleDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RD_BookedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RD_Booked_Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RD_Raffle_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RD_Raffle_block")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RD_User_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("raffleDetails");
                });

            modelBuilder.Entity("RaffleKing.Models.basic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("basics");
                });

            modelBuilder.Entity("RaffleKing.Models.raffle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("R_BlockGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_BlockStartFrom")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("R_DrawnAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("R_FullDecription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("R_MainImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("R_ShortDecription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("R_ThumbnailImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("R_TicketPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("R_Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("R_Total_Available")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_Total_Booked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("R_UniqueRaffleCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("raffles");
                });
#pragma warning restore 612, 618
        }
    }
}
